project_id = "dlayrpnmfnbjlxgnkczv"

[functions.loadrite]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.agent-action]
verify_jwt = false

[functions.agent-stream]
verify_jwt = false